In [ ]:
# Array Creation
# ------------------


# np.array(): Creates an array.

# np.zeros(): Creates an array filled with zeros.

# np.ones(): Creates an array filled with ones.

# np.empty(): Creates an uninitialized array.

# np.arange(): Creates an array with a range of values.

# np.linspace(): Creates an array with linearly spaced values.

# np.random(): Contains functions for generating random numbers.



# Array Manipulation
#--------------------


# np.reshape(): Changes the shape of an array.

# np.flatten(): Flattens a multi-dimensional array.

# np.transpose(): Transposes an array.

# np.concatenate(): Joins arrays together.

# np.split(): Splits an array into multiple sub-arrays.



# Array Operations
#-----------------


# np.add(): Adds elements of arrays.

# np.subtract(): Subtracts elements of arrays.

# np.multiply(): Multiplies elements of arrays.

# np.divide(): Divides elements of arrays.

# np.dot(): Dot product of two arrays.

# np.cross(): Cross product of two arrays.

# np.power(): Raises elements of arrays to powers.



# Statistical Functions
#----------------------


# np.mean(): Computes the mean of array elements.

# np.median(): Computes the median of array elements.

# np.std(): Computes the standard deviation of array elements.

# np.var(): Computes the variance of array elements.

# np.sum(): Sums array elements.

# np.min(): Finds the minimum value in an array.

# np.max(): Finds the maximum value in an array.



# Linear Algebra
#----------------


# np.linalg.inv(): Computes the inverse of a matrix.

# np.linalg.det(): Computes the determinant of a matrix.

# np.linalg.eig(): Computes the eigenvalues and eigenvectors of a matrix.

# np.linalg.svd(): Performs singular value decomposition.


# Others
#--------


# np.where(): Returns elements based on a condition.

# np.unique(): Finds unique elements of an array.

# np.sort(): Sorts an array

In [ ]:
import numpy as np

In [ ]:
list = [1,2,3,4,5]
np.array(list)

array([1, 2, 3, 4, 5])

In [ ]:
matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)


array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,21,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,10))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(1,20,15)

array([ 1.        ,  2.35714286,  3.71428571,  5.07142857,  6.42857143,
        7.78571429,  9.14285714, 10.5       , 11.85714286, 13.21428571,
       14.57142857, 15.92857143, 17.28571429, 18.64285714, 20.        ])

In [ ]:
np.random.rand(5)

array([0.91575973, 0.97689256, 0.37589003, 0.49648297, 0.59588388])

In [ ]:
np.random.rand(5,5)

array([[0.43703296, 0.89582947, 0.5090053 , 0.01877172, 0.69106952],
       [0.90127981, 0.72144492, 0.8755904 , 0.42483746, 0.53009011],
       [0.6339657 , 0.27147677, 0.61295734, 0.06636328, 0.28778109],
       [0.52973339, 0.79214314, 0.66913867, 0.79198991, 0.68545263],
       [0.74473282, 0.62847335, 0.94863715, 0.19679603, 0.49968024]])

In [ ]:
np.random.randint(1,10)

4

In [ ]:
np.random.randint(1,6,10)

array([1, 5, 2, 5, 3, 4, 4, 1, 1, 1])

In [ ]:
# Array and Methods

a = np.arange(25)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
r = np.random.randint(0,50,10)

r

array([ 1,  9, 19, 43,  0, 17, 48, 44, 33,  4])

In [ ]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
a.max()

24

In [ ]:
r.max()

48

In [ ]:
a.min()

0

In [ ]:
r.min()

0

In [ ]:
r.argmax()

6

In [ ]:
a.argmax()

24

In [ ]:
r.argmin()

4

In [ ]:
a.argmin()

0

In [ ]:
a.shape

(25,)

In [ ]:
r.shape

(10,)

In [ ]:
a.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
a.shape

(25,)

In [ ]:
a.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
a.reshape(25,1).shape

(25, 1)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
r.dtype

dtype('int64')

In [ ]:
list1 = [1.1,2,3.5,4,5]
list2 = np.array(list1)
list2


array([1.1, 2. , 3.5, 4. , 5. ])

In [ ]:
list2.dtype

dtype('float64')

In [ ]:
ar =np.arange(11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Slice

ar[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
ar[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
# Broadcasting

ar[0:5] = 1000
ar

array([1000, 1000, 1000, 1000, 1000,    5,    6,    7,    8,    9,   10])

In [ ]:
ar # reset the 71th code

array([1000, 1000, 1000, 1000, 1000,    5,    6,    7,    8,    9,   10])

In [ ]:
s = ar[:5]
s

array([1000, 1000, 1000, 1000, 1000])

In [ ]:
# Replace

s[:] = 123
s

array([123, 123, 123, 123, 123])

In [ ]:
ar # Memory problem using .copy methed

array([123, 123, 123, 123, 123,   5,   6,   7,   8,   9,  10])

In [ ]:
ar # reset 88th row

array([123, 123, 123, 123, 123,   5,   6,   7,   8,   9,  10])

In [ ]:
s = ar[0:5].copy()
s

array([123, 123, 123, 123, 123])

In [ ]:
s[:] = 999
s

array([999, 999, 999, 999, 999])

In [ ]:
ar # now not any have a memory problem

array([123, 123, 123, 123, 123,   5,   6,   7,   8,   9,  10])

In [ ]:
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mat1.shape

(3, 3)

In [ ]:
mat1[0]

array([1, 2, 3])

In [ ]:
mat1[1]

array([4, 5, 6])

In [ ]:
mat1[2]

array([7, 8, 9])

In [ ]:
mat1[1][1]

5

In [ ]:
#Creating sample array
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Get a value at an index
arr[8]

8

In [ ]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [ ]:
# Getting individual element value
arr_2d[1,0]

20

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [ ]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])